# Generated by Django 4.2.4 on 2023-08-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='is_stressed',
            field=models.BooleanField(null=True),
        ),
    ]
