# Generated by Django 4.2.4 on 2023-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_usermessage_is_stressed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='is_stressed',
            field=models.IntegerField(default=0),
        ),
    ]
