# Generated by Django 4.2.4 on 2023-09-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_usermessage_is_stressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
