# Generated by Django 4.2.4 on 2023-09-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_formscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formscore',
            name='form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
